### PR TITLE
fix: decouple from Remote/SSH module + guard missing-module paths (hotfix)

### LINKED ISSUE #628: Exception when loading confluent plugin in latest 2026.2 EAP
IntelliJ IDEA 2026.2 EAP
Build #IU-262.8117.19, built on June 18, 2026
Source revision: f0c4c63511770
Expiration date: July 18, 2026
Runtime version: 25.0.3+9-b508.4 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
Exception reporter ID: 2102251e00889e3-368e-4f76-94c5-71237ff74682
JCEF version: 144.0.15-262-b37
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048MiB
Cores: 8

```java
2026-06-18 12:54:55,741 [  10672] SEVERE - #c.i.o.w.i.ToolWindowManagerImpl - Cannot process toolwindow KafkaToolWindow
java.lang.NoClassDefFoundError: com/intellij/ssh/config/unified/SshConfig
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3010)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2420)
	at java.base/java.io.ObjectStreamClass.getPrivateMethod(ObjectStreamClass.java:1396)
	at java.base/java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:372)
	at java.base/java.io.ObjectStreamClass$Caches$1.computeValue(ObjectStreamClass.java:93)
	at java.base/java.io.ObjectStreamClass$Caches$1.computeValue(ObjectStreamClass.java:90)
	at java.base/java.io.ClassCache$1.computeValue(ClassCache.java:78)
	at java.base/java.io.ClassCache$1.computeValue(ClassCache.java:75)
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:204)
	at java.base/java.lang.ClassValue.get(ClassValue.java:152)
	at java.base/java.io.ClassCache.get(ClassCache.java:89)
	at java.base/java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:329)
	at java.base/java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:227)
	at io.confluent.intellijplugin.core.settings.ConnectionSettingsBase$PluginObjectInputStream.readClassDescriptor(ConnectionSettingsBase.kt:462)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1902)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1785)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2101)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1620)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:487)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:445)
	at io.confluent.intellijplugin.core.settings.ConnectionSettingsBase$Companion.decode64(ConnectionSettingsBase.kt:132)
	at io.confluent.intellijplugin.core.settings.ConnectionSettingsBase$Companion.unpackData(ConnectionSettingsBase.kt:243)
	at io.confluent.intellijplugin.core.settings.ConnectionSettingsBase.loadState(ConnectionSettingsBase.kt:374)
	at io.confluent.intellijplugin.core.settings.GlobalConnectionSettings.loadState(GlobalConnectionSettings.kt:42)
	at io.confluent.intellijplugin.core.settings.GlobalConnectionSettings.loadState(GlobalConnectionSettings.kt:19)
	at com.intellij.configurationStore.ComponentStoreImpl$doInitComponent$2.invoke(ComponentStoreImpl.kt:646)
	at com.intellij.configurationStore.ComponentStoreImpl$doInitComponent$2.invoke(ComponentStoreImpl.kt:645)
	at com.intellij.configurationStore.ComponentStoreImpl$initComponent$nonCancelableInvocator$1.invokeSuspend(ComponentStoreImpl.kt:161)
	at com.intellij.configurationStore.ComponentStoreImpl$initComponent$nonCancelableInvocator$1.invoke(ComponentStoreImpl.kt)
	at com.intellij.configurationStore.ComponentStoreImpl$initComponent$nonCancelableInvocator$1.invoke(ComponentStoreImpl.kt)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent$suspendImpl(ComponentStoreImpl.kt:212)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.openapi.components.impl.stores.IComponentStore.initComponent$default(IComponentStore.kt:27)
	at com.intellij.serviceContainer.ContainerUtilKt.initializeComponentOrLightService(containerUtil.kt:63)
	at com.intellij.serviceContainer.LightServiceInstanceSupport$LightServiceInstanceInitializer.createInstance(LightServiceInstanceSupport.kt:59)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:181)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndspatched(Undispatched.kt:67)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:43)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:179)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:20)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:360)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:134)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:53)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:164)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:29)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:154)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:112)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext$suspendImpl(LazyInstanceHolder.kt:104)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext(LazyInstanceHolder.kt)
	at com.intellij.serviceContainer.ComponentManagerImplKt$doGetOrCreateInstanceBlocking$1.invokeSuspend(ComponentManagerImpl.kt:1698)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:112)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$BuildersKt__BuildersKt(Builders.kt:87)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlockingWithParallelismCompensation(Builders.kt:63)
	at kotlinx.coroutines.BuildersKt.runBlockingWithParallelismCompensation(Unknown Source)
	at kotlinx.coroutines.internal.intellij.IntellijCoroutines.runBlockingWithParallelismCompensation(intellij.kt:48)
	at com.intellij.util.IntelliJCoroutinesFacade.runBlockingWithParallelismCompensation(IntelliJCoroutinesFacade.kt:35)
	at com.intellij.serviceContainer.ComponentManagerImplKt.runBlockingInitialization$lambda$0(ComponentManagerImpl.kt:1829)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext$lambda$0(context.kt:96)
	at com.intellij.concurrency.ThreadContext.resetThreadContext(threadContext.kt:295)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:95)
	at com.intellij.serviceContainer.ComponentManagerImplKt.runBlockingInitialization(ComponentManagerImpl.kt:1814)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doGetOrCreateInstanceBlocking(ComponentManagerImpl.kt:1697)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1686)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:798)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:736)
	at io.confluent.intellijplugin.core.settings.GlobalConnectionSettings$Companion.getInstance(GlobalConnectionSettings.kt:193)
	at io.confluent.intellijplugin.core.settings.manager.RfsConnectionDataManager.getConnectionStorage(RfsConnectionDataManager.kt:138)
	at io.confluent.intellijplugin.core.settings.manager.RfsConnectionDataManager.getAppConnections(RfsConnectionDataManager.kt:108)
	at io.confluent.intellijplugin.core.settings.manager.RfsConnectionDataManager.getConnections(RfsConnectionDataManager.kt:39)
	at io.confluent.intellijplugin.core.settings.manager.RfsConnectionDataManager.getConnectionsByGroupId(RfsConnectionDataManager.kt:67)
	at io.confluent.intellijplugin.toolwindow.KafkaToolWindowFactory.shouldBeAvailable(KafkaToolWindowFactory.kt:23)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:372)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:356)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$beanToTask(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$2$1$1.invokeSuspend(ToolWindowSetInitializer.kt:396)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:610)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runDefaultDispatcherTask(CoroutineScheduler.kt:1194)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:906)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:775)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:762)
Caused by: java.lang.ClassNotFoundException: com.intellij.ssh.config.unified.SshConfig PluginClassLoader(plugin=PluginMainDescriptor(name=Confluent, id=com.intellij.bigdatatools.kafka, version=253.25910.1, isBundled=false, path=~\AppData\Roaming\JetBrains\IntelliJIdea2026.2\plugins\intellij), packagePrefix=null, state=active, parents=ContentModuleDescriptor(id=intellij.json.syntax, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=JSON, id=com.intellij.modules.json, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\json), ContentModuleDescriptor(id=intellij.json, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=JSON, id=com.intellij.modules.json, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\json), ContentModuleDescriptor(id=intellij.platform.vcs.log.graph) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\lib), ContentModuleDescriptor(id=intellij.platform.vcs.log) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\lib), ContentModuleDescriptor(id=intellij.platform.smRunner, loadingRule=REQUIRED) <- PluginMainDescriptor(name=Test Runner, id=intellij.testRunner.plugin, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\platform-testRunner-plugin), ContentModuleDescriptor(id=intellij.platform.structureView) <- PluginMainDescriptor(name=Structure View, id=intellij.structureView.plugin, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\platform-structureView-plugin), ContentModuleDescriptor(id=intellij.platform.todo) <- PluginMainDescriptor(name=TODO Comments, id=intellij.todo.plugin, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\platform-todo-plugin), ContentModuleDescriptor(id=intellij.platform.bookmarks, loadingRule=REQUIRED) <- PluginMainDescriptor(name=Bookmarks Manager, id=intellij.bookmarks.plugin, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\platform-bookmarks-plugin), ContentModuleDescriptor(id=intellij.platform.vcs.dvcs) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\lib), ContentModuleDescriptor(id=intellij.platform.vcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\lib), ContentModuleDescriptor(id=intellij.platform.vcs.log.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\lib), ContentModuleDescriptor(id=intellij.platform.vcs.dvcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\lib), ContentModuleDescriptor(id=intellij.json.backend, loadingRule=REQUIRED) <- PluginMainDescriptor(name=JSON, id=com.intellij.modules.json, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\json), ContentModuleDescriptor(id=intellij.json.structureView) <- PluginMainDescriptor(name=JSON, id=com.intellij.modules.json, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\json), ContentModuleDescriptor(id=intellij.json.backend.regexp) <- PluginMainDescriptor(name=JSON, id=com.intellij.modules.json, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\json), ContentModuleDescriptor(id=intellij.json.networknt.wrapper, loadingRule=REQUIRED) <- PluginMainDescriptor(name=JSON, id=com.intellij.modules.json, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\json), ContentModuleDescriptor(id=intellij.platform.collaborationTools) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\lib), ContentModuleDescriptor(id=intellij.spring.boot.shared) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.run.shared) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.run.free) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, 
isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.core) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.core.ide) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.el) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.mvc) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.configYaml) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.properties.datasource) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.yaml.datasource) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.run) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.maven.shared) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.core.copyright) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.cron) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.cron.properties) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.cron.yaml) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.data) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), ContentModuleDescriptor(id=intellij.spring.boot.json) <- PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), PluginMainDescriptor(name=JSON, id=com.intellij.modules.json, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\json), PluginMainDescriptor(name=Spring Boot, id=com.intellij.spring.boot, version=262.8117.19, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA Ultimate\plugins\spring-boot-plugin), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 95 more
```

### PR DESCRIPTION
**Pull request by noeldevelops**
# Summary
Hotfix for `NoClassDefFoundError` for `com.intellij.ssh.*` classes (`SshConfig`, `SshConfigVisibility`) - Sentry has been seeing this event quite a bit lately

**TL;DR:** the code catches/mitigates an old but quiet failure mode -- The plugin references `com.intellij.ssh.*` but never declares a dependency on that module, assuming it would ship with the IDE. 

[Latest updates to the platform](https://plugins.jetbrains.com/docs/intellij/api-changes-list-2026.html#java-plugin-20261) make it so these classes are no longer reachable from the plugin's classloader without that declaration, and certain IDE flavors like Webstorm and Community edition never shipped with the module. 

### User-facing changes
Instead of a red error message and crash, users get a nice message in the settings when SSH module is not loaded. No change when the module is reachable.

### Follow up coming
⚠️ The [next step](https://github.com/confluentinc/intellij/issues/634) will be to make sure `plugin.xml` declares this as an explicit dependency, but it will be done against `main` since it will affect a bigger surface area than a hotfix warrants. 

### Steps to Reproduce
To repro on EAP version of IntelliJ - install the latest plugin version and restart the IDE to see the crash. You will notice in Community/Webstorm that the plugin if already installed is not running/shown in sidebar since it cannot load.

------------ 

# AI-generated Summary (partially edited by moi)
Hotfix for the highest-volume Sentry cluster (~122 events): `NoClassDefFoundError` for `com.intellij.ssh.*` (`SshConfig`, `SshConfigVisibility`) in IDEs where the IntelliJ **Remote/SSH** module isn't reachable from the plugin's classloader.

Closes https://github.com/confluentinc/intellij/issues/628

## Why the module isn't reachable — two triggers

The plugin references `com.intellij.ssh.*` but never declares a dependency on that module, so:

- **Module absent** — flavors like **WebStorm** / IDEA **Community** don't bundle Remote/SSH at all.
- **Module present but classloader-isolated** — #628 is on **IDEA Ultimate 2026.2 EAP**, which *does* bundle SSH, but the plugin's `PluginClassLoader` chain doesn't include it since 2026.2 tightened per-module classloading. So this `com.intellij.ssh.*` reference that used to resolve transitively now fails even though the classes are available.

Both throw the `ClassNotFoundException` → `NoClassDefFoundError` on `com.intellij.ssh.config.unified.SshConfig`.

## Root cause: the persisted connection model is SSH-coupled

`KafkaConnectionData.tunnel` is a **persisted** field of type `ConnectionSshTunnelDataLegacy`, and that class exposed `getSshConfig(): SshConfig` as a **member**. Java serialization builds an `ObjectStreamClass` for it on **every read *and* write** (`getState`→`packData`→`encode64` and `loadState`→`unpackData`→`decode64`), reflecting all declared method signatures — so resolving `getSshConfig`'s `SshConfig` return type throws `NoClassDefFoundError` wherever the module isn't reachable, for **every connection, including the untouched `DEFAULT` tunnel**. This is why the crash hit both startup deserialization **and** "Apply" (save), even with no SSH configured — and why (in early AI iterations of this fix) guarding one serialization entry point kept exposing the next.

## The fix

**1. Decouple `ConnectionSshTunnelData.kt` from the module.** 
Move `getSshConfig` from a member to a top-level **extension function**. Fields and the explicit `serialVersionUID` are unchanged → persisted data stays compatible.

**2. Guard the two paths where SSH classes referenced directly, not via serialization**:
- **Settings UI** — `SshTunnelComponent.<init>` hard-references `com.intellij.ssh.ui.*`. Now made nullable and built only when available, with an "SSH tunneling requires the Remote/SSH plugin" info row otherwise.
- **Connect-time** — `BdtSshTunnelService.createIfRequired` returns `null` (degrades like a disabled tunnel) when the module is unavailable, before constructing the `SshConfig`-referencing `ConnectionSshTunnelInfo`.

**3. Defensive catches for deserialization paths** (general, not SSH-specific):
- A per-connection `catch (Throwable)` boundary around `unpackData` in `loadState` — no deserialization failure can crash startup.
- Per-property `catch (NoClassDefFoundError)` in `unpackData` (loop + unhandled-props). `unpackData` is reached from five call sites and the boundary wraps only one, so these are the cross-caller safety net.

## Verification

- `./gradlew compileKotlin` → **BUILD SUCCESSFUL** (pre-existing warnings only).
- **Manually verified on IDEA Ultimate 2026.2 EAP** (the classloader-isolated case): install, enable, open Settings, and **Apply** all succeed with no crash.
- No unit test: the guarded branches are classloader-dependent (the SSH classes *are* reachable on the test classpath, so the unavailable branch can't run without synthetic-classloader infra), and the model fix is a structural change verified by compile + manual run.

## Known separate issue (not a regression from this PR)

Disabling the plugin **while the Settings dialog is open** logs `PluginException: Can't instantiate configurable` from `DynamicPlugins.unloadPlugins` — a dynamic plugin-unload race, unrelated to SSH (platform-only stack, configurable classes untouched, bundle key present). Tracked separately.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: src/io/confluent/intellijplugin/core/connection/tunnel/BdtSshTunnelService.kt [hunk 1]
```diff
@@ -43,6 +44,16 @@ object BdtSshTunnelService {
...
 
+        // The IntelliJ SSH/Remote module (com.intellij.ssh.*) is not bundled in every IDE flavor
+        // (e.g. WebStorm). A tunnel can only be enabled here if the config was synced in from an
+        // IDE that had the module; constructing ConnectionSshTunnelInfo below hard-references
+        // com.intellij.ssh.config.unified.SshConfig and would throw NoClassDefFoundError. Degrade
+        // like a disabled tunnel instead of crashing the connect. See SshModuleAvailability.
+        if (!SshModuleAvailability.isAvailable) {
+            logger.warn("SSH tunnel is enabled but the Remote/SSH module is not available; skipping tunnel.")
+            return null
+        }
```
[the remark this answers is not in the document]
Comment (noeldevelops) [reply src/io/confluent/intellijplugin/core/connection/tunnel/BdtSshTunnelService.kt]: (Claude generated reply) Thanks — I dug into this and the guard is reachable in practice, so leaving it as-is for the hotfix. Under StackMapTable verification (which Kotlin emits), the JVM resolves symbolic references **lazily**: `BdtSshTunnelService` loads and links fine despite `SshSession`/`SshUiData` in its descriptors, and `NoClassDefFoundError` only fires when an instruction actually touches a missing type. The guard returns before line 61 (`ConnectionSshTunnelInfo(...)`, the first SSH-touching instruction), so the early `return null` runs before anything links. The Sentry data backs this up: across ~122 events the crashes are only ever at field-init (`SshTunnelComponent.<init>`) and reflection (`getDeclaredMethods0` in deserialization), never at plain method entry. The fully robust fix — moving the SSH-referencing code off the always-loaded path via an optional `<depends>`/`ssh.xml` — is tracked as a follow-up on `main`, where it can be verified across IDE flavors.

File: src/io/confluent/intellijplugin/core/connection/tunnel/ui/SshModuleAvailability.kt [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+            true
+        } catch (e: ClassNotFoundException) {
+            logger.info("SSH/Remote module not available; SSH tunnel UI will be disabled.", e)
+            false
+        } catch (e: LinkageError) {
+            // NoClassDefFoundError and friends: the class resolved partially but its
+            // dependencies are missing. Treat as unavailable.
+            logger.info("SSH/Remote module only partially available; SSH tunnel UI will be disabled.", e)
+            false
+        }
```
[the remark this answers is not in the document]
Comment (noeldevelops) [reply src/io/confluent/intellijplugin/core/connection/tunnel/ui/SshModuleAvailability.kt:30]: (Claude generated reply) Good call — fixed in 8dca5965. The expected "module unavailable" case now logs a plain INFO message and the throwable is relegated to DEBUG, so WebStorm/non-SSH IDEs do not get a stack trace at INFO.

File: src/io/confluent/intellijplugin/settings/ConnectionSettingsBase.kt [hunk 3]
```diff
@@ -446,6 +446,13 @@ abstract class ConnectionSettingsBase : PersistentStateComponent<ConnectionPersi
...
             } catch (_: ClassNotFoundException) {
                 null
+            } catch (e: LinkageError) {
+                // The class itself resolved but references types that are absent in this IDE
+                // flavor (e.g. com.intellij.ssh.* when the Remote/SSH module is not present).
+                // Treat as not-loadable so deserialization degrades gracefully instead of
+                // throwing NoClassDefFoundError up through loadState at startup.
+                logger.warn("Could not link class '$fqn' (missing optional module?), skipping.", e)
+                null
             }
```
[the remark this answers is not in the document]
Comment (noeldevelops) [reply src/io/confluent/intellijplugin/settings/ConnectionSettingsBase.kt]: (Claude generated reply) Agreed — narrowed to `NoClassDefFoundError` in 8dca5965. That is the actual observed failure here (it is the top frame in #628), and narrowing avoids swallowing genuine binary-incompatibility errors (`VerifyError`, `UnsupportedClassVersionError`, `IncompatibleClassChangeError`).

File: src/io/confluent/intellijplugin/settings/ConnectionSettingsBase.kt [hunk 4]
```diff
@@ -459,7 +466,16 @@ abstract class ConnectionSettingsBase : PersistentStateComponent<ConnectionPersi
...
-            val localDescriptor = ObjectStreamClass.lookup(actualClass) ?: return baseDescriptor
+            // ObjectStreamClass.lookup() reflects over the class's declared members. If those
+            // member signatures reference types absent in this IDE flavor (e.g. com.intellij.ssh.*),
+            // the JDK throws NoClassDefFoundError here. Swallow it so startup loadState degrades
+            // gracefully (falls back to the serialized descriptor) instead of crashing.
+            val localDescriptor = try {
+                ObjectStreamClass.lookup(actualClass)
+            } catch (e: LinkageError) {
+                logger.warn("Could not introspect class '${actualClass.name}' (missing optional module?), using serialized descriptor.", e)
+                return baseDescriptor
```
[the remark this answers is not in the document]
Comment (noeldevelops) [reply src/io/confluent/intellijplugin/settings/ConnectionSettingsBase.kt]: Same fix applied in 8dca5965 — narrowed this `ObjectStreamClass.lookup()` catch to `NoClassDefFoundError`.

**Review by eguicf — APPROVED** [review]
Thanks for the fix @noeldevelops! I wasn't able to reproduce the crash directly due to different config (OS) to the original report. Instead verified the fix at the code level:

**Structural check**: compared the compiled `ConnectionSshTunnelDataLegacy` class before vs. after. 
- Pre-fix, it has a member `getSshConfig(): SshConfig`, so `com.intellij.ssh.*` is baked into the class's own method table. 
- Post-fix, that method is moved to a top-level extension function — the class has zero references to `com.intellij.ssh.*`.

**Behavioral check**: claude code wrote a small harness that loads the class through a `ClassLoader` which deliberately blocks `com.intellij.ssh.*` (simulating the module being unreachable), then does a real `ObjectOutputStream/ObjectInputStream` round-trip — the exact code path from the crash.
- Pre-fix: throws `NoClassDefFoundError: com/intellij/ssh/config/unified/SshConfig`, reproducing the reported error.
- Post-fix: serializes/deserializes cleanly, no error.

This should confirm the fix removes the actual trigger.
